version: '3.8'
services:
  zettedele-frontend:
    container_name: zettedele-frontend
    build: ./${FOLDER}
    ports:
      - "${REACT_EXTERNAL_PORT}:${REACT_INTERNAL_PORT}"
    stdin_open: true
    tty: true
    volumes:
      - './${FOLDER}:/app'
      - 'node_modules:/app/node_modules'
volumes:
  node_modules: