name: ZettedeleFrontende Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build and run the Docker image
      run: docker-compose up -d --force-recreate --build
